services:
  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: wow
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: concert_wow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
