packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  argon2: true
  cpu-features: false
  esbuild: false
  msw: true
  prisma: true
  protobufjs: false
  sharp: true
  ssh2: false
  unrs-resolver: true
